define

##########---------- Relationships ----------##########
data_dependence sub relation,
    relates has_data_dependence, relates is_data_dependence;

VariableDeclarator plays data_dependence:has_data_dependence;
Parameter plays data_dependence:has_data_dependence, plays data_dependence:is_data_dependence;
Stmt plays data_dependence:has_data_dependence, plays data_dependence:is_data_dependence;
Expr plays data_dependence:has_data_dependence, plays data_dependence:is_data_dependence;