define

##########---------- Relationships ----------##########
data_dependence sub relation,
    relates has_data_dependence, relates is_data_dependence;

VariableDeclarator plays has_data_dependence;
Parameter plays has_data_dependence, plays is_data_dependence;
Stmt plays has_data_dependence, plays is_data_dependence;
Expr plays has_data_dependence, plays is_data_dependence;