define

##########---------- Relationships ----------##########
identifier_access sub relationship
    relates has_identifier_access, relates is_identifier_access;
has_identifier_access sub role;
is_identifier_access sub role;

FieldDeclaration plays has_identifier_access;
VariableDeclarator plays has_identifier_access;
Parameter plays has_identifier_access;
SimpleName plays is_identifier_access;
NameExpr plays is_identifier_access;