version: '2.1'
services:
  grakn:
    stdin_open: true
    tty: true
    hostname: grakn
    build:
      context: .
      dockerfile: Dockerfile-grakn
    ports:
      - "4567:4567"
      - "9042:9042"
      - "9160:9160"