define

##########---------- Attributes ----------##########
total_loc sub attribute datatype long;
source_loc sub attribute datatype long;
blank_loc sub attribute datatype long;
comment_loc sub attribute datatype long;
logical_loc sub attribute datatype long;

CompilationUnit
    has total_loc
    has source_loc
    has blank_loc
    has comment_loc
    has logical_loc;
