define

cyclomatic_complexity sub attribute datatype long;

GoFuncDeclArtifact has cyclomatic_complexity;
JavaMethodDeclarationArtifact has cyclomatic_complexity;
JavascriptFunctionDeclarationArtifact has cyclomatic_complexity;
PythonFunctionDefArtifact has cyclomatic_complexity;
