define

cyclomaticComplexity sub attribute, datatype long;

GoFuncDeclArtifact has cyclomaticComplexity;
JavaMethodDeclarationArtifact has cyclomaticComplexity;
JavascriptFunctionDeclarationArtifact has cyclomaticComplexity;
PythonFunctionDefArtifact has cyclomaticComplexity;
RubyDefArtifact has cyclomaticComplexity;
PhpStmtFunctionArtifact has cyclomaticComplexity;
CsharpMethodDeclarationArtifact has cyclomaticComplexity;
CplusplusCPPASTFunctionDefinitionArtifact has cyclomaticComplexity;
CplusplusCPPASTFunctionDeclaratorArtifact has cyclomaticComplexity;
BashFunctionDefElementArtifact has cyclomaticComplexity;