define

cyclomaticComplexity sub attribute datatype long;

GoFuncDeclArtifact has cyclomaticComplexity;
JavaMethodDeclarationArtifact has cyclomaticComplexity;
JavascriptFunctionDeclarationArtifact has cyclomaticComplexity;
PythonFunctionDefArtifact has cyclomaticComplexity;
