define

##########---------- Attributes ----------##########
control_value sub attribute, datatype boolean;

##########---------- Relationships ----------##########
control_flow sub relations,
    relates has_control_flow, relates is_control_flow
    has control_value;

#todo: use CallableDeclaration instead
ConstructorDeclaration plays has_control_flow, plays is_control_flow;
MethodDeclaration plays has_control_flow, plays is_control_flow;

VariableDeclarator plays has_control_flow, plays is_control_flow;
Parameter plays has_control_flow, plays is_control_flow;
Stmt plays has_control_flow, plays is_control_flow;
Expr plays has_control_flow, plays is_control_flow;