define

#has_identifier_access
JavaSimpleNameArtifact plays has_identifier_access;

#is_identifier_access
JavaSimpleNameArtifact plays is_identifier_access;
JavaQualifiedNameArtifact plays is_identifier_access;