define

#has_identifier_access
JavaSimpleNameArtifact plays identifier_access:has_identifier_access;

#is_identifier_access
JavaSimpleNameArtifact plays identifier_access:is_identifier_access;
JavaQualifiedNameArtifact plays identifier_access:is_identifier_access;